consul:
  command: -server -bootstrap -rejoin 
  image: progrium/consul:latest
  hostname: "registry"
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
micro:
  command: --registry_address=registry:8500 --api_handler=rpc api
  image: microhq/micro:latest
  links:
    - consul
  ports:
    - "8080:8080"

download:
  build: ./srv/download
  command: --registry_address=registry:8500
  links:
    - consul
